name: Secret File
description: Write a secret to a local file during a workflow
branding:
  icon: lock
  color: purple
inputs:
  secret:
    description: The secret to write to a file
    required: true
  b64-decode:
    description: Indicates whether to base64 decode the secret value
    required: true
    default: "true"
  outputs:
    file:
      description: The file the secret was written to
runs:
  using: node20
  main: index.js
